# Generated by Django 4.1 on 2022-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
